// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trawl/source/contacts/open/v1/open.proto

package contactsopenv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactsRecord struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Ref                string                     `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Name               string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SortName           *string                    `protobuf:"bytes,3,opt,name=sort_name,json=sortName,proto3,oneof" json:"sort_name,omitempty"`
	Aka                []string                   `protobuf:"bytes,4,rep,name=aka,proto3" json:"aka,omitempty"`
	Tags               []string                   `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Emails             []*ContactValue            `protobuf:"bytes,6,rep,name=emails,proto3" json:"emails,omitempty"`
	Phones             []*ContactValue            `protobuf:"bytes,7,rep,name=phones,proto3" json:"phones,omitempty"`
	Addresses          []*ContactValue            `protobuf:"bytes,8,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Accounts           map[string]*IdentifierList `protobuf:"bytes,9,rep,name=accounts,proto3" json:"accounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotation         *string                    `protobuf:"bytes,10,opt,name=annotation,proto3,oneof" json:"annotation,omitempty"`
	AnnotationStatedAt *string                    `protobuf:"bytes,11,opt,name=annotation_stated_at,json=annotationStatedAt,proto3,oneof" json:"annotation_stated_at,omitempty"`
	// The contact card as the source states it, in the vCard vocabulary shared
	// by Apple Contacts, Google Contacts and CardDAV.
	GivenName                *string         `protobuf:"bytes,12,opt,name=given_name,json=givenName,proto3,oneof" json:"given_name,omitempty"`
	MiddleName               *string         `protobuf:"bytes,13,opt,name=middle_name,json=middleName,proto3,oneof" json:"middle_name,omitempty"`
	FamilyName               *string         `protobuf:"bytes,14,opt,name=family_name,json=familyName,proto3,oneof" json:"family_name,omitempty"`
	PreviousFamilyName       *string         `protobuf:"bytes,15,opt,name=previous_family_name,json=previousFamilyName,proto3,oneof" json:"previous_family_name,omitempty"`
	NamePrefix               *string         `protobuf:"bytes,16,opt,name=name_prefix,json=namePrefix,proto3,oneof" json:"name_prefix,omitempty"`
	NameSuffix               *string         `protobuf:"bytes,17,opt,name=name_suffix,json=nameSuffix,proto3,oneof" json:"name_suffix,omitempty"`
	Nickname                 *string         `protobuf:"bytes,18,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	PhoneticGivenName        *string         `protobuf:"bytes,19,opt,name=phonetic_given_name,json=phoneticGivenName,proto3,oneof" json:"phonetic_given_name,omitempty"`
	PhoneticMiddleName       *string         `protobuf:"bytes,20,opt,name=phonetic_middle_name,json=phoneticMiddleName,proto3,oneof" json:"phonetic_middle_name,omitempty"`
	PhoneticFamilyName       *string         `protobuf:"bytes,21,opt,name=phonetic_family_name,json=phoneticFamilyName,proto3,oneof" json:"phonetic_family_name,omitempty"`
	PhoneticOrganizationName *string         `protobuf:"bytes,22,opt,name=phonetic_organization_name,json=phoneticOrganizationName,proto3,oneof" json:"phonetic_organization_name,omitempty"`
	OrganizationName         *string         `protobuf:"bytes,23,opt,name=organization_name,json=organizationName,proto3,oneof" json:"organization_name,omitempty"`
	DepartmentName           *string         `protobuf:"bytes,24,opt,name=department_name,json=departmentName,proto3,oneof" json:"department_name,omitempty"`
	JobTitle                 *string         `protobuf:"bytes,25,opt,name=job_title,json=jobTitle,proto3,oneof" json:"job_title,omitempty"`
	Birthday                 *string         `protobuf:"bytes,26,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Note                     *string         `protobuf:"bytes,27,opt,name=note,proto3,oneof" json:"note,omitempty"`
	UrlAddresses             []*ContactValue `protobuf:"bytes,28,rep,name=url_addresses,json=urlAddresses,proto3" json:"url_addresses,omitempty"`
	SocialProfiles           []*ContactValue `protobuf:"bytes,29,rep,name=social_profiles,json=socialProfiles,proto3" json:"social_profiles,omitempty"`
	InstantMessageAddresses  []*ContactValue `protobuf:"bytes,30,rep,name=instant_message_addresses,json=instantMessageAddresses,proto3" json:"instant_message_addresses,omitempty"`
	Dates                    []*ContactValue `protobuf:"bytes,31,rep,name=dates,proto3" json:"dates,omitempty"`
	ContactRelations         []*ContactValue `protobuf:"bytes,32,rep,name=contact_relations,json=contactRelations,proto3" json:"contact_relations,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ContactsRecord) Reset() {
	*x = ContactsRecord{}
	mi := &file_trawl_source_contacts_open_v1_open_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactsRecord) ProtoMessage() {}

func (x *ContactsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_source_contacts_open_v1_open_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactsRecord.ProtoReflect.Descriptor instead.
func (*ContactsRecord) Descriptor() ([]byte, []int) {
	return file_trawl_source_contacts_open_v1_open_proto_rawDescGZIP(), []int{0}
}

func (x *ContactsRecord) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ContactsRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactsRecord) GetSortName() string {
	if x != nil && x.SortName != nil {
		return *x.SortName
	}
	return ""
}

func (x *ContactsRecord) GetAka() []string {
	if x != nil {
		return x.Aka
	}
	return nil
}

func (x *ContactsRecord) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ContactsRecord) GetEmails() []*ContactValue {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *ContactsRecord) GetPhones() []*ContactValue {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *ContactsRecord) GetAddresses() []*ContactValue {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ContactsRecord) GetAccounts() map[string]*IdentifierList {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ContactsRecord) GetAnnotation() string {
	if x != nil && x.Annotation != nil {
		return *x.Annotation
	}
	return ""
}

func (x *ContactsRecord) GetAnnotationStatedAt() string {
	if x != nil && x.AnnotationStatedAt != nil {
		return *x.AnnotationStatedAt
	}
	return ""
}

func (x *ContactsRecord) GetGivenName() string {
	if x != nil && x.GivenName != nil {
		return *x.GivenName
	}
	return ""
}

func (x *ContactsRecord) GetMiddleName() string {
	if x != nil && x.MiddleName != nil {
		return *x.MiddleName
	}
	return ""
}

func (x *ContactsRecord) GetFamilyName() string {
	if x != nil && x.FamilyName != nil {
		return *x.FamilyName
	}
	return ""
}

func (x *ContactsRecord) GetPreviousFamilyName() string {
	if x != nil && x.PreviousFamilyName != nil {
		return *x.PreviousFamilyName
	}
	return ""
}

func (x *ContactsRecord) GetNamePrefix() string {
	if x != nil && x.NamePrefix != nil {
		return *x.NamePrefix
	}
	return ""
}

func (x *ContactsRecord) GetNameSuffix() string {
	if x != nil && x.NameSuffix != nil {
		return *x.NameSuffix
	}
	return ""
}

func (x *ContactsRecord) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *ContactsRecord) GetPhoneticGivenName() string {
	if x != nil && x.PhoneticGivenName != nil {
		return *x.PhoneticGivenName
	}
	return ""
}

func (x *ContactsRecord) GetPhoneticMiddleName() string {
	if x != nil && x.PhoneticMiddleName != nil {
		return *x.PhoneticMiddleName
	}
	return ""
}

func (x *ContactsRecord) GetPhoneticFamilyName() string {
	if x != nil && x.PhoneticFamilyName != nil {
		return *x.PhoneticFamilyName
	}
	return ""
}

func (x *ContactsRecord) GetPhoneticOrganizationName() string {
	if x != nil && x.PhoneticOrganizationName != nil {
		return *x.PhoneticOrganizationName
	}
	return ""
}

func (x *ContactsRecord) GetOrganizationName() string {
	if x != nil && x.OrganizationName != nil {
		return *x.OrganizationName
	}
	return ""
}

func (x *ContactsRecord) GetDepartmentName() string {
	if x != nil && x.DepartmentName != nil {
		return *x.DepartmentName
	}
	return ""
}

func (x *ContactsRecord) GetJobTitle() string {
	if x != nil && x.JobTitle != nil {
		return *x.JobTitle
	}
	return ""
}

func (x *ContactsRecord) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *ContactsRecord) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *ContactsRecord) GetUrlAddresses() []*ContactValue {
	if x != nil {
		return x.UrlAddresses
	}
	return nil
}

func (x *ContactsRecord) GetSocialProfiles() []*ContactValue {
	if x != nil {
		return x.SocialProfiles
	}
	return nil
}

func (x *ContactsRecord) GetInstantMessageAddresses() []*ContactValue {
	if x != nil {
		return x.InstantMessageAddresses
	}
	return nil
}

func (x *ContactsRecord) GetDates() []*ContactValue {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *ContactsRecord) GetContactRelations() []*ContactValue {
	if x != nil {
		return x.ContactRelations
	}
	return nil
}

type ContactValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         *string                `protobuf:"bytes,2,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Primary       *bool                  `protobuf:"varint,3,opt,name=primary,proto3,oneof" json:"primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactValue) Reset() {
	*x = ContactValue{}
	mi := &file_trawl_source_contacts_open_v1_open_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactValue) ProtoMessage() {}

func (x *ContactValue) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_source_contacts_open_v1_open_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactValue.ProtoReflect.Descriptor instead.
func (*ContactValue) Descriptor() ([]byte, []int) {
	return file_trawl_source_contacts_open_v1_open_proto_rawDescGZIP(), []int{1}
}

func (x *ContactValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ContactValue) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *ContactValue) GetPrimary() bool {
	if x != nil && x.Primary != nil {
		return *x.Primary
	}
	return false
}

type IdentifierList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifierList) Reset() {
	*x = IdentifierList{}
	mi := &file_trawl_source_contacts_open_v1_open_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifierList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifierList) ProtoMessage() {}

func (x *IdentifierList) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_source_contacts_open_v1_open_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifierList.ProtoReflect.Descriptor instead.
func (*IdentifierList) Descriptor() ([]byte, []int) {
	return file_trawl_source_contacts_open_v1_open_proto_rawDescGZIP(), []int{2}
}

func (x *IdentifierList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_trawl_source_contacts_open_v1_open_proto protoreflect.FileDescriptor

const file_trawl_source_contacts_open_v1_open_proto_rawDesc = "" +
	"\n" +
	"(trawl/source/contacts/open/v1/open.proto\x12\x1dtrawl.source.contacts.open.v1\"\xba\x10\n" +
	"\x0eContactsRecord\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\tsort_name\x18\x03 \x01(\tH\x00R\bsortName\x88\x01\x01\x12\x10\n" +
	"\x03aka\x18\x04 \x03(\tR\x03aka\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12C\n" +
	"\x06emails\x18\x06 \x03(\v2+.trawl.source.contacts.open.v1.ContactValueR\x06emails\x12C\n" +
	"\x06phones\x18\a \x03(\v2+.trawl.source.contacts.open.v1.ContactValueR\x06phones\x12I\n" +
	"\taddresses\x18\b \x03(\v2+.trawl.source.contacts.open.v1.ContactValueR\taddresses\x12W\n" +
	"\baccounts\x18\t \x03(\v2;.trawl.source.contacts.open.v1.ContactsRecord.AccountsEntryR\baccounts\x12#\n" +
	"\n" +
	"annotation\x18\n" +
	" \x01(\tH\x01R\n" +
	"annotation\x88\x01\x01\x125\n" +
	"\x14annotation_stated_at\x18\v \x01(\tH\x02R\x12annotationStatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"given_name\x18\f \x01(\tH\x03R\tgivenName\x88\x01\x01\x12$\n" +
	"\vmiddle_name\x18\r \x01(\tH\x04R\n" +
	"middleName\x88\x01\x01\x12$\n" +
	"\vfamily_name\x18\x0e \x01(\tH\x05R\n" +
	"familyName\x88\x01\x01\x125\n" +
	"\x14previous_family_name\x18\x0f \x01(\tH\x06R\x12previousFamilyName\x88\x01\x01\x12$\n" +
	"\vname_prefix\x18\x10 \x01(\tH\aR\n" +
	"namePrefix\x88\x01\x01\x12$\n" +
	"\vname_suffix\x18\x11 \x01(\tH\bR\n" +
	"nameSuffix\x88\x01\x01\x12\x1f\n" +
	"\bnickname\x18\x12 \x01(\tH\tR\bnickname\x88\x01\x01\x123\n" +
	"\x13phonetic_given_name\x18\x13 \x01(\tH\n" +
	"R\x11phoneticGivenName\x88\x01\x01\x125\n" +
	"\x14phonetic_middle_name\x18\x14 \x01(\tH\vR\x12phoneticMiddleName\x88\x01\x01\x125\n" +
	"\x14phonetic_family_name\x18\x15 \x01(\tH\fR\x12phoneticFamilyName\x88\x01\x01\x12A\n" +
	"\x1aphonetic_organization_name\x18\x16 \x01(\tH\rR\x18phoneticOrganizationName\x88\x01\x01\x120\n" +
	"\x11organization_name\x18\x17 \x01(\tH\x0eR\x10organizationName\x88\x01\x01\x12,\n" +
	"\x0fdepartment_name\x18\x18 \x01(\tH\x0fR\x0edepartmentName\x88\x01\x01\x12 \n" +
	"\tjob_title\x18\x19 \x01(\tH\x10R\bjobTitle\x88\x01\x01\x12\x1f\n" +
	"\bbirthday\x18\x1a \x01(\tH\x11R\bbirthday\x88\x01\x01\x12\x17\n" +
	"\x04note\x18\x1b \x01(\tH\x12R\x04note\x88\x01\x01\x12P\n" +
	"\rurl_addresses\x18\x1c \x03(\v2+.trawl.source.contacts.open.v1.ContactValueR\furlAddresses\x12T\n" +
	"\x0fsocial_profiles\x18\x1d \x03(\v2+.trawl.source.contacts.open.v1.ContactValueR\x0esocialProfiles\x12g\n" +
	"\x19instant_message_addresses\x18\x1e \x03(\v2+.trawl.source.contacts.open.v1.ContactValueR\x17instantMessageAddresses\x12A\n" +
	"\x05dates\x18\x1f \x03(\v2+.trawl.source.contacts.open.v1.ContactValueR\x05dates\x12X\n" +
	"\x11contact_relations\x18  \x03(\v2+.trawl.source.contacts.open.v1.ContactValueR\x10contactRelations\x1aj\n" +
	"\rAccountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.trawl.source.contacts.open.v1.IdentifierListR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_sort_nameB\r\n" +
	"\v_annotationB\x17\n" +
	"\x15_annotation_stated_atB\r\n" +
	"\v_given_nameB\x0e\n" +
	"\f_middle_nameB\x0e\n" +
	"\f_family_nameB\x17\n" +
	"\x15_previous_family_nameB\x0e\n" +
	"\f_name_prefixB\x0e\n" +
	"\f_name_suffixB\v\n" +
	"\t_nicknameB\x16\n" +
	"\x14_phonetic_given_nameB\x17\n" +
	"\x15_phonetic_middle_nameB\x17\n" +
	"\x15_phonetic_family_nameB\x1d\n" +
	"\x1b_phonetic_organization_nameB\x14\n" +
	"\x12_organization_nameB\x12\n" +
	"\x10_department_nameB\f\n" +
	"\n" +
	"_job_titleB\v\n" +
	"\t_birthdayB\a\n" +
	"\x05_note\"t\n" +
	"\fContactValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x19\n" +
	"\x05label\x18\x02 \x01(\tH\x00R\x05label\x88\x01\x01\x12\x1d\n" +
	"\aprimary\x18\x03 \x01(\bH\x01R\aprimary\x88\x01\x01B\b\n" +
	"\x06_labelB\n" +
	"\n" +
	"\b_primary\"(\n" +
	"\x0eIdentifierList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06valuesB\\ZZgithub.com/opentrawl/opentrawl/trawlkit/proto/trawl/source/contacts/open/v1;contactsopenv1b\x06proto3"

var (
	file_trawl_source_contacts_open_v1_open_proto_rawDescOnce sync.Once
	file_trawl_source_contacts_open_v1_open_proto_rawDescData []byte
)

func file_trawl_source_contacts_open_v1_open_proto_rawDescGZIP() []byte {
	file_trawl_source_contacts_open_v1_open_proto_rawDescOnce.Do(func() {
		file_trawl_source_contacts_open_v1_open_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trawl_source_contacts_open_v1_open_proto_rawDesc), len(file_trawl_source_contacts_open_v1_open_proto_rawDesc)))
	})
	return file_trawl_source_contacts_open_v1_open_proto_rawDescData
}

var file_trawl_source_contacts_open_v1_open_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trawl_source_contacts_open_v1_open_proto_goTypes = []any{
	(*ContactsRecord)(nil), // 0: trawl.source.contacts.open.v1.ContactsRecord
	(*ContactValue)(nil),   // 1: trawl.source.contacts.open.v1.ContactValue
	(*IdentifierList)(nil), // 2: trawl.source.contacts.open.v1.IdentifierList
	nil,                    // 3: trawl.source.contacts.open.v1.ContactsRecord.AccountsEntry
}
var file_trawl_source_contacts_open_v1_open_proto_depIdxs = []int32{
	1,  // 0: trawl.source.contacts.open.v1.ContactsRecord.emails:type_name -> trawl.source.contacts.open.v1.ContactValue
	1,  // 1: trawl.source.contacts.open.v1.ContactsRecord.phones:type_name -> trawl.source.contacts.open.v1.ContactValue
	1,  // 2: trawl.source.contacts.open.v1.ContactsRecord.addresses:type_name -> trawl.source.contacts.open.v1.ContactValue
	3,  // 3: trawl.source.contacts.open.v1.ContactsRecord.accounts:type_name -> trawl.source.contacts.open.v1.ContactsRecord.AccountsEntry
	1,  // 4: trawl.source.contacts.open.v1.ContactsRecord.url_addresses:type_name -> trawl.source.contacts.open.v1.ContactValue
	1,  // 5: trawl.source.contacts.open.v1.ContactsRecord.social_profiles:type_name -> trawl.source.contacts.open.v1.ContactValue
	1,  // 6: trawl.source.contacts.open.v1.ContactsRecord.instant_message_addresses:type_name -> trawl.source.contacts.open.v1.ContactValue
	1,  // 7: trawl.source.contacts.open.v1.ContactsRecord.dates:type_name -> trawl.source.contacts.open.v1.ContactValue
	1,  // 8: trawl.source.contacts.open.v1.ContactsRecord.contact_relations:type_name -> trawl.source.contacts.open.v1.ContactValue
	2,  // 9: trawl.source.contacts.open.v1.ContactsRecord.AccountsEntry.value:type_name -> trawl.source.contacts.open.v1.IdentifierList
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_trawl_source_contacts_open_v1_open_proto_init() }
func file_trawl_source_contacts_open_v1_open_proto_init() {
	if File_trawl_source_contacts_open_v1_open_proto != nil {
		return
	}
	file_trawl_source_contacts_open_v1_open_proto_msgTypes[0].OneofWrappers = []any{}
	file_trawl_source_contacts_open_v1_open_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trawl_source_contacts_open_v1_open_proto_rawDesc), len(file_trawl_source_contacts_open_v1_open_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trawl_source_contacts_open_v1_open_proto_goTypes,
		DependencyIndexes: file_trawl_source_contacts_open_v1_open_proto_depIdxs,
		MessageInfos:      file_trawl_source_contacts_open_v1_open_proto_msgTypes,
	}.Build()
	File_trawl_source_contacts_open_v1_open_proto = out.File
	file_trawl_source_contacts_open_v1_open_proto_goTypes = nil
	file_trawl_source_contacts_open_v1_open_proto_depIdxs = nil
}
